### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by GeckoEidechse** [GeckoEidechse/OpenHomeAutomationBot#1]
Things planned

- [ ] Basic
  - [ ] Only check posts since last time subreddit was accessed
    - [ ] Store timestamp of last run somewhere
  - [ ] Parse content of link posts to news articles
  - [ ] Leave comment about automated post
- [ ] Docs
  - [ ] How to setup with e.g. cron job
- [ ] Extra
  - [ ] Option to lock comments to redirect redditors to main post
        (most useful for question/discussion post where OP might be unaware of crosspost)
